#!/usr/bin/env python

__version__ = "0.2.x"

import sys

import clusterbank.scripting.allocation

if __name__ == "__main__":
    try:
        allocations = clusterbank.scripting.allocation.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if allocations:
        for allocation in allocations:
            print allocation.id, allocation
