#!/usr/bin/env python

import sys

import clusterbank.scripting.admin

if __name__ == "__main__":
    try:
        permissions = clusterbank.scripting.admin.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if permissions:
        for permission in permissions:
            print permission
