#!/usr/bin/env python

__version__ = "0.2.x"

import sys

import clusterbank.scripting.charge

if __name__ == "__main__":
    try:
        charges = clusterbank.scripting.charge.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if charges:
        for charge in charges:
            print charge.id, charge
