#!/usr/bin/env python

import sys

import clusterbank.scripting.hold

if __name__ == "__main__":
    try:
        holds = clusterbank.scripting.hold.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if holds:
        for hold in holds:
            print hold.id, hold
