#!/usr/bin/env python

import sys

from sqlalchemy.exceptions import DBAPIError

import clusterbank.model
from clusterbank import scripting
from clusterbank.scripting import ScriptingError

def run ():
    clusterbank.model.metadata.create_all()

if __name__ == "__main__":
    try:
        run()
    except KeyboardInterrupt:
        sys.exit(ScriptingError.STATUS)
    except ScriptingError, e:
        print >> sys.stderr, e
        sys.exit(e.STATUS)
    except DBAPIError, e:
        print >> sys.stderr, e
        sys.exit(1)
