#!/usr/bin/env python

__version__ = "0.2.x"

import sys

from sqlalchemy.exceptions import DBAPIError

from clusterbank.scripting import lien, ScriptingError
from clusterbank.config import load_config, ConfigurationError

if __name__ == "__main__":
    try:
        load_config()
    except ConfigurationError, e:
        print >> sys.stderr, e
        sys.exit(e.STATUS)
    try:
        liens = lien.run()
    except KeyboardInterrupt:
        sys.exit(ScriptingError.STATUS)
    except ConfigurationError, e:
        print >> sys.stderr, e
        sys.exit(ScriptingError.STATUS)
    except ScriptingError, e:
        print >> sys.stderr, e
        sys.exit(e.STATUS)
    except DBAPIError, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if liens:
        for lien in liens:
            print lien.id, lien
