#!/usr/bin/env python

import sys

import clusterbank.scripting.lien

if __name__ == "__main__":
    try:
        liens = clusterbank.scripting.lien.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if liens:
        for lien in liens:
            print lien.id, lien
