#!/usr/bin/env python

__version__ = "0.2.x"

import sys

from sqlalchemy.exceptions import DBAPIError

from clusterbank.scripting import refund, ScriptingError

if __name__ == "__main__":
    try:
        refunds = refund.run()
    except KeyboardInterrupt:
        sys.exit(ScriptingError.STATUS)
    except ConfigurationError, e:
        print >> sys.stderr, e
        sys.exit(ScriptingError.STATUS)
    except ScriptingError, e:
        print >> sys.stderr, e
        sys.exit(e.STATUS)
    except DBAPIError, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if refunds:
        for refund in refunds:
            print refund.id, refund
