#!/usr/bin/env python

import sys

import clusterbank.scripting.request

if __name__ == "__main__":
    try:
        requests = clusterbank.scripting.request.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if requests:
        for request in requests:
            print request.id, request
