#!/usr/bin/env python

import sys

import clusterbank.scripting.refund

if __name__ == "__main__":
    try:
        refunds = clusterbank.scripting.refund.run()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    if refunds:
        for refund in refunds:
            print refund.id, refund
