#!/usr/bin/env python

import sys

import clusterbank.scripting.cbank

if __name__ == "__main__":
    try:
        entities = clusterbank.scripting.cbank.main()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception, e:
        print >> sys.stderr, e
        sys.exit(1)
    
    for entity in entities:
        print entity.id, entity
