.Dd 29 August 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-report-holds
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op options
.Sh DESCRIPTION
For each applicable active hold report the date that the hold was created; the associated resource, project, and user; and the amount held.
.Sh OPTIONS
.Bl -tag
.It Fl u Ar user
Report holds associated
.Ar user .
If no
.Ar project
is specified, projects that
.Ar user
is a member of will be included in the report.
.It Fl p Ar project
Report holds on
.Ar project .
.It Fl r Ar resource
Report holds for
.Ar resource .
(default specified in
.Pa /etc/clusterbank.conf )
.It Fl a Ar date
Report holds created after (and including)
.Ar date .
.It Fl b Ar date
Report holds created before (and excluding)
.Ar date .
.It Fl c
Report associated comments.
.El
.Sh EXAMPLES
Report holds on the project 'grail' associated with users 'monty' and 'python':
.Bd -filled -offset indent
.Nm
-p grail -u monty -u python
.Ed
.Pp
Report holds associated with 'monty' between 5 October 1969 and 5 December 1974:
.Bd -filled -offset indent
.Nm
-u monty -a 1969-10-05 -b 1974-12-05
.Ed
.Sh FILES
.Bl -item
.It
.Pa /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-report 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
