.Dd 29 August 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-detail
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Ar entity id
.Op Ar ...
.Sh DESCRIPTION
Display details for the
.Ar entity
specified by
.Ar id .
.Pp
Possible values for
.Ar entity
are: 
.Bl -tag
.It allocations
Display all data for individual allocaitons.
.It holds
Display all data for individual holds.
.It charges
Display all data for individual charges.
.It refunds
Display all data for individual refunds.
.El
.Pp
Any non-ambiguous value for
.Ar entity
is valid. Therefore, the following commands are equivalent:
.D1
.Nm
allocations
.D1
.Nm
allocation
.D1
.Nm
all
.D1
.Nm
a
.Sh SEE ALSO
.Xr cbank 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
