.Dd 26 November 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-report-charges
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op options
.Sh DESCRIPTION
For each applicable charge report the associated date, resource, project, and user, as well as the effective amount charged.
.Sh OPTIONS
.Bl -tag
.It Fl u Ar user
Report charges associated with
.Ar user .
.Ar If no
.Ar project
is specified, projects that
.Ar user
is a member of will be included in the report.
.It Fl p Ar project
Report charges to
.Ar project .
.It Fl r Ar resource
Report charges for
.Ar resource .
(default specified in
.Pa /etc/clusterbank.conf )
.It Fl a Ar date
Report charges created after (and including)
.Ar date .
.It Fl b Ar date
Report charges created before (and excluding)
.Ar date .
.It Fl c
Report associated comments.
.It Fl l
Do not truncate long string fields.
.El
.Sh EXAMPLES
Generate a report of all charges associated with the current user:
Report charges to the project 'grail' associated with users 'monty' and 'python':
.Bd -filled -offset indent
.Nm
-p grail -u monty -u python
.Ed
.Pp
Report charges associated with 'monty' between 5 October 1969 and 5 December 1974:
.Bd -filled -offset indent
.Nm
-u monty -a 1969-10-05 -b 1974-12-05
.Ed
.Sh FILES
.Bl -item
.It
.Pa /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-report 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
