.Dd 21 January 2009
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-list-allocations
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op options
.Sh DESCRIPTION
For each applicable allocation list the expiration date, the associated resource and project, the number of jobs, the total amount charged, and the amount available to be charged.
.Sh OPTIONS
.Bl -tag
.It Fl u Ar user
Report jobs and charges for
.Ar user .
If no
.Ar project
is specified, projects that
.Ar user
is a member of will be included in the list.
.It Fl p Ar project
Report allocations to
.Ar project .
.It Fl r Ar resource
Report allocations for
.Ar resource .
(default specified in
.Pa /etc/clusterbank.conf )
.It Fl a Ar date
Report jobs and charges that occured after (and including)
.Ar date .
Allocations that expire after
.Ar date
will be included in the list.
.It Fl b Ar date
Report jobs and charges that occured before (and excluding)
.Ar date .
Allocations that start before
.Ar date
will be included in the list.
.It Fl c
Report associated comments.
.It Fl l
Do not truncate long string fields.
.El
.Sh EXAMPLES
The project 'grail' by users 'monty' and 'python':
.Bd -filled -offset indent
.Nm
-p grail -u monty -u python
.Ed
.Pp
Allocations to the projects of 'monty' between 5 October 1969 and 5 December 1974:
.Bd -filled -offset indent
.Nm
-u monty -a 1969-10-05 -b 1974-12-05
.Ed
.Sh FILES
.Bl -item
.It
.Pa /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-list 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
