.Dd 29 August 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-new-allocation
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op Fl r Ar resource
.Op Fl s Ar date
.Op Fl e Ar date
.Op Fl c Ar comment
.Ar project
.Ar amount
.Sh DESCRIPTION
allocate an
.Ar amount
of a resource to a
.Ar project .
.Pp
Available options:
.Bl -tag
.It Fl r
Specify which resource to allocate. (default specified in
.Pa /etc/clusterbank.conf )
.It Fl s
Specify when the allocation becomes usable. (default now)
.It Fl e
Specify when the allocation expires. (default next year)
.It Fl c
Supply an informative comment.
.El
.Sh FILES
.Bl -tag
.It /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-new 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
