.Dd 1 August 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-report-users
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op OPTIONS
.Sh DESCRIPTION
For each applicable user, report the number of charges, and total amount charged. Users can view their own charges, project owners can view charges to their projects, and admins can view all charges.
.Sh OPTIONS
.Bl -tag
.It Fl u , -user Ar user
Display charges for
.Ar user .
.It Fl p , -project Ar project
Display the members of and charges to
.Ar project .
.It Fl r , -resource Ar resource
Display charges to
.Ar resource .
(default specified in
.Pa /etc/clusterbank.conf )
.It Fl a , -after Ar date
Display charges that occured after (and including)
.Ar date .
.It Fl b , -before Ar date
Display charges that occured before (and excluding)
.Ar date .
.El
.Sh EXAMPLES
Generate the default users report:
.D1 cbank report users
or
.D1 cbank users
.Pp
Report charges to and by members of the projects 'grail' and 'circus':
.D1 cbank report users -p grail -p circus
.Pp
Report charges by user 'monty' between 5 October 1969 and 5 December 1974.
.D1 cbank report users -u monty -a 1969-10-5 -b 1974-12-5
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
