.Dd 21 January 2009
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-list
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op Ar list
.Sh DESCRIPTION
Generate a clusterbank
.Ar list :
.Bl -tag
.It users
Report aggregate data by user.
.It projects (default)
Report aggregate data by project.
.It allocations
Report aggregate data by allocation.
.It holds
Report active holds.
.It jobs
Report recorded jobs.
.It charges
Report individual charges.
.El
.Pp
Additional arguments are passed to the specific
.Ar list .
.Sh EXAMPLES
Any non-ambiguous value for
.Ar list
is valid. Therefore, the following commands are equivalent:
.Bd -filled -offset indent
.Nm
allocations
.Ed
.Bd -filled -offset indent -compact
.Nm
allocation
.Ed
.Bd -filled -offset indent -compact
.Nm
all
.Ed
.Bd -filled -offset indent -compact
.Nm
a
.Ed
.Sh FILES
.Bl -item
.It
.Pa /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-list-users 7 ,
.Xr cbank-list-projects 7 ,
.Xr cbank-list-allocations 7 ,
.Xr cbank-list-holds 7 ,
.Xr cbank-list-jobs 7 ,
.Xr cbank-list-charges 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
