.Dd 21 January 2009
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-list-jobs
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op options
.Sh DESCRIPTION
For each applicable job list the id, name, user, account, and duration, as well as the effective amount charged.
.Sh OPTIONS
.Bl -tag
.It Fl u Ar user
Report jobs associated with
.Ar user .
.It Fl p Ar project
Report jobs for
.Ar project .
.It Fl r Ar resource
Report jobs on
.Ar resource .
(default specified in
.Pa /etc/clusterbank.conf )
.It Fl a Ar date
Report jobs that end after
.Ar date .
.It Fl b Ar date
Report jobs that start before or on
.Ar date .
.It Fl l
Do not truncate long string fields.
.El
.Sh EXAMPLES
Report jobs for the project 'grail' associated with users 'monty' or 'python':
.Bd -filled -offset indent
.Nm
-p grail -u monty -u python
.Ed
.Pp
Report jobs associated with 'monty' that ran between 5 October 1969 and 5 December 1974:
.Bd -filled -offset indent
.Nm
-u monty -a 1969-10-05 -b 1974-12-05
.Ed
.Sh FILES
.Bl -item
.It
.Pa /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-list 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
