.Dd 21 January 2009
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op Ar subcommand
.Sh DESCRIPTION
A metacommand that dispatches to another
.Ar subcommand :
.Bl -tag
.It new
Create new enties (allocations, charges, etc.).
.It list (default)
Generate lists.
.It detail
Display all data for a given entity.
.El
.Pp
Additional arguments are passed to the specific
.Ar subcommand .
.Sh EXAMPLES
Any non-ambiguous value for
.Ar subcommand
is valid. Therefore, the following commands are equivalent:
.Bd -filled -offset indent
.Nm
list
.Ed
.Bd -filled -offset indent -compact
.Nm
re
.Ed
.Bd -filled -offset indent -compact
.Nm
r
.Ed
.Sh FILES
.Bl -item
.It
.Pa /etc/clusterbank.conf
Global configuration and defaults.
.El
.Sh SEE ALSO
.Xr cbank-new 7 ,
.Xr cbank-list 7 ,
.Xr cbank-detail 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
