.Dd 29 August 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-new
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Ar entity
.Sh DESCRIPTION
Create a clusterbank
.Ar entity :
.Bl -tag
.It allocation
Allocate resources to a project.
.It hold
Place a hold on a project's allocation(s).
.It charge
Charge a project's allocation(s).
.It refund
Refund an existing charge.
.El
.Pp
Additional arguments are passed to the specific
.Ar entity
command.
.Pp
Any non-ambiguous value for
.Ar entity
is valid. Therefore, the following commands are equivalent:
.D1
.Nm
allocation
.D1
.Nm
all
.D1
.Nm
a
.Sh SEE ALSO
.Xr cbank 7 ,
.Xr cbank-new-allocation 7 ,
.Xr cbank-new-hold 7 ,
.Xr cbank-new-charge 7 ,
.Xr cbank-new-refund 7
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
