.Dd 1 August 2008
.Os Python 2.x
.Dt CBANK 7 USD
.Sh NAME
.Nm cbank-report-projects
.Nd clusterbank command-line interface
.Sh SYNOPSIS
.Nm
.Op OPTIONS
.Sh DESCRIPTION
For each applicable project, report the amount available to be charged, the current number of charges, and the total amount charged.
.Sh OPTIONS
.Bl -tag
.It Fl u , -user Ar user
Display projects of and charges by
.Ar user .
.It Fl p , -project Ar project
Display charges to
.Ar project .
.It Fl r , -resource Ar resource
Display charges to
.Ar resource .
(default specified in
.Pa /etc/clusterbank.conf )
.It Fl a , -after Ar date
Display charges that occured after (and including)
.Ar date .
.It Fl b , -before Ar date
Display charges that occured before (and excluding)
.Ar date .
.El
.Sh EXAMPLES
Generate a report of all charges for the current users's projects:
.D1 cbank report projects
or
.D1 cbank projects
.Pp
or
.D1 cbank
Report charges to the project 'grail' by users 'monty' and 'python':
.D1 cbank report projects -p grail -u monty -u python
.Pp
Report charges by and to the projects of 'monty' between 5 October 1969 and 5 December 1974.
.D1 cbank report projects -u monty -a 1969-10-5 -b 1974-12-5
.Sh AUTHORS
.An Jonathon Anderson
.Ad janderso@alcf.anl.gov
.Sh BUGS
Submit bug reports to the clusterbank trac at
.Ad http://trac.mcs.anl.gov/projects/clusterbank
